// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAakt4y4uoEnzHTunA08Vc2Pa5iyW_tbhI',
    appId: '1:48001430255:web:12ab713ed0691a9d2d211a',
    messagingSenderId: '48001430255',
    projectId: 'ecommerce-afeaa',
    authDomain: 'ecommerce-afeaa.firebaseapp.com',
    storageBucket: 'ecommerce-afeaa.firebasestorage.app',
    measurementId: 'G-2CS7H1T9XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv8w-Q3eFhoQjJQrL7Z_dXxTHjdmqpgI0',
    appId: '1:48001430255:android:7c5348be69e0a18a2d211a',
    messagingSenderId: '48001430255',
    projectId: 'ecommerce-afeaa',
    storageBucket: 'ecommerce-afeaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKwiX1QOBqtdcN0ozAiHQIIcxOSl9oXbg',
    appId: '1:48001430255:ios:7cb761267ea9b1282d211a',
    messagingSenderId: '48001430255',
    projectId: 'ecommerce-afeaa',
    storageBucket: 'ecommerce-afeaa.firebasestorage.app',
    iosBundleId: 'com.example.emoccerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKwiX1QOBqtdcN0ozAiHQIIcxOSl9oXbg',
    appId: '1:48001430255:ios:7cb761267ea9b1282d211a',
    messagingSenderId: '48001430255',
    projectId: 'ecommerce-afeaa',
    storageBucket: 'ecommerce-afeaa.firebasestorage.app',
    iosBundleId: 'com.example.emoccerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAakt4y4uoEnzHTunA08Vc2Pa5iyW_tbhI',
    appId: '1:48001430255:web:0d90e45d07a2cfe92d211a',
    messagingSenderId: '48001430255',
    projectId: 'ecommerce-afeaa',
    authDomain: 'ecommerce-afeaa.firebaseapp.com',
    storageBucket: 'ecommerce-afeaa.firebasestorage.app',
    measurementId: 'G-M6LT650CVM',
  );

}